#!/bin/bash

source format.sh

check_deps

TWOFA_DIRECTORY="$HOME/.2fa"

mkdir -p "$TWOFA_DIRECTORY"

arg=$1

case $arg in
	[hH] | [hH][eE][lL][pP] )
		print_header

		echo -e " ${FORMAT_BOLD}USAGE:${FORMAT_NORM} ./2fa [ACTION] ${FROMAT_DIM}?${FORMAT_NORM}[LABEL] [OPTION]..."
		echo ""	
		echo -e " ${FORMAT_BOLD}ACTIONS:${FORMAT_NORM}"
		echo -e "\thelp, h \t\t- show this text"
		echo -e "\tinit, i \t\t- create service"
		echo -e "\tcode, c \t\t- get 2fa code for certain service"
		# echo ""	
		# echo "Options:"
		;;
	[iI] | [iI][nN][iI][tT] ) source ./2fa_init.sh -d="$TWOFA_DIRECTORY" "$@"
		;;
	[cC] | [cC][oO][dD][eE] ) source ./2fa_code.sh -s="$TWOFA_DIRECTORY/$2"
		;;
esac