#!/usr/bin/env bash

source head.sh
source format.sh
source tools.sh

check_deps

mkdir -p "$FASH_DIRECTORY"
mkdir -p "$FASH_DIRECTORY_ACCOUNTS"

arg=$1

print_help() {
	print_help_usage_head "${FASH_COMMAND} [ACTION] ${FORMAT_LYELLOW}?${FORMAT_NORM}[ACCOUNT] [OPTION]..."
	echo ""
	print_help_head "ACTIONS"
	print_help_command "help,\th" "show help"
	print_help_command "init,\ti" "add a new account"
	print_help_command "code,\tc" "get 2fa code for account"
	print_help_command "list,\tls" "print accounts"
	print_help_command "remove,\trm" "remove account"
}

case ${arg} in
	[hH] | [hH][eE][lL][pP])
		print_header
		print_help
		echo ""
	;;
	[iI] | [iI][nN][iI][tT])
		bash "$FASH_DIRECTORY_BIN/2fash_init.sh" -d="$FASH_DIRECTORY_ACCOUNTS" "$@"
	;;
	[cC] | [cC][oO][dD][eE])
		bash "./2fash_code.sh" -a="$2" "$@" # todo: fix
	;;
	[lL][sS] | [lL][iI][sS][tT])
		bash "$FASH_DIRECTORY_BIN/2fash_list.sh" "$@"
	;;
	[rR][mM] | [rR][eE][mM][oO][vV][eE])
		bash "$FASH_DIRECTORY_BIN/2fash_remove.sh" -a="$2" "$@"
	;;
	*)
		print_header
		print_help
		echo ""
	;;
esac
