#!/usr/bin/env bash

[[ -z "$FASH_DIRECTORY" ]] && FASH_DIRECTORY="$HOME/.2fash"
[[ -z "$FASH_DIRECTORY_BIN" ]] && FASH_DIRECTORY_BIN="$FASH_DIRECTORY/bin"
[[ -z "$FASH_DIRECTORY_ACCOUNTS" ]] && FASH_DIRECTORY_ACCOUNTS="$FASH_DIRECTORY/accounts"

mkdir -p "$FASH_DIRECTORY"
mkdir -p "$FASH_DIRECTORY_BIN"
mkdir -p "$FASH_DIRECTORY_ACCOUNTS"

2fash() {
	bash "$FASH_DIRECTORY_BIN/2fash" "$@"
}